### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by bp-alex** [csabigee/nobo#1]
I was wondering if there were any instructions on deploying this? https://github.com/csabigee/nobo/wiki/Building-the-custom-thermostat is presently empty.

**Comment by csabigee** [comment]
I made a fully functional device with a custom PCB, enclosure, that replaces the factory thermostat:
https://www.hackster.io/csabigee/nobo-wireless-thermostat-01f106
All source files are available.

If You don't want to manufacture the PCB and enclosure, You can use an ESP devboard too and wire it to the heater panel (You still need to salvage the pins from the original thermostat to make the connection).
I recommend an ESP8266 board, because the heater panel is only able to provide ~120mA current, and the ESP32 board were keep resetting for me.
